apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: todos
  POSTGRES_USER: balman
  POSTGRES_PASSWORD: admin1234
  POSTGRES_HOST: todolist-datastore